### PR TITLE
Add support for aarch64 linux

### PR DESCRIPTION
**Pull request by mrcmunir**
Pre build binary for aarch64 linux added support.

### CODE REVIEW

**Comment by 1whatleytay** [comment]
Oh hey I was just looking for this.

Well I was looking for the macOS aarch64 build but I'll take what I can get 👍

**Review by 1whatleytay — APPROVED** [review]

**Comment by mrcmunir** [comment]
I don't have a mac but it should work same this this starting from mac x86_64 script you just need to change the ARCH to arm64 and rebuild

**Comment by Macdu** [comment]
Sorry, this PR is a bit out of date. If you update it to the new format (should be fairly easy, just update the CI to add a new linux-latest runner and use the arm64-linux-release vcpkg community triplet, hopefully this should work, you might have to install an aarch64 compiler in the CI), I'll approve it.

**Comment by mrcmunir** [comment]
I'll see what I can do I may need help on arm64-linux-release vcpkg triplet since I don't see any indicative examples that already use arm64.
For the rest without problems it is easy to update it to ffmpeg 5.1.2  .

**Comment by Macdu** [comment]
Sorry, I don't receive notifications for this repository. You can ping me on discord if I don't respond. You can take a look at what I did for the Android version (https://github.com/Macdu/ffmpeg-core/tree/android) or ask me for help directly if needed. For the android version, I made both a static and dynamic version (I can't use the static version right now on Android because of the LGPL license) and also a custom triplet in order not to make the debug build. That's not necessary for the linux aarch64 version.

**Comment by FantasyGmm** [comment]
> Sorry, I don't receive notifications for this repository. You can ping me on discord if I don't respond. You can take a look at what I did for the Android version ([https://github.com/Macdu/ffmpeg-core/tree/android](https://hub.fantasygmm.top/Macdu/ffmpeg-core/tree/android)) or ask me for help directly if needed. For the android version, I made both a static and dynamic version (I can't use the static version right now on Android because of the LGPL license) and also a custom triplet in order not to make the debug build. That's not necessary for the linux aarch64 version.

How to build these prebuilts lib, how should I choose lib versions

**Pull request closed without merging**
