### PR TITLE
Build and use universal binary on macOS

### PR DESCRIPTION
**Pull request by KhoraLee**
Universal binaries can be used on all kind of build(arm64, x86_64, universal).

### CODE REVIEW

**Comment by sunho** [comment]
Is this ready to be merged?

**Review by Macdu — APPROVED** [review]
LGTM, I can merge if you think the PR is ready

**Comment by Macdu** [comment]
LGTM, can I merge @KhoraLee or you are still planning to do some modifications?

**Comment by KhoraLee** [comment]
@Macdu It's ready now.

**Review by Macdu — APPROVED** [review]

**Pull request merged**
